// =============================================
// EMOTIONEN-KARTEN: 5 Kategorien Lernkarten
// Für Kinder 3–8 Jahre
// =============================================

// Kategorie 1: Situation + falsches Emoji → richtige Emotion erkennen
const KAT1 = [
  {
    type: 'situation-emoji-check',
    charVariant: 'kid',
    charEmotion: 'happy',
    sceneEmojis: ['🍦', '🧒'],
    sceneBeschreibung: 'Kind bekommt ein riesiges Eis',
    wrongEmoji: '😢',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['glücklich', 'traurig', 'müde'],
    richtig: 'glücklich',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'boy',
    charEmotion: 'sad',
    sceneEmojis: ['🚂', '💥'],
    sceneBeschreibung: 'Das Lieblingsspielzeug ist kaputt gegangen',
    wrongEmoji: '😀',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['traurig', 'glücklich', 'aufgeregt'],
    richtig: 'traurig',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'girl',
    charEmotion: 'angry',
    sceneEmojis: ['🧸', '👋'],
    sceneBeschreibung: 'Jemand nimmt dem Kind das Spielzeug weg',
    wrongEmoji: '🙂',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['wütend', 'glücklich', 'stolz'],
    richtig: 'wütend',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'kid',
    charEmotion: 'scared',
    sceneEmojis: ['🐕', '🔊', '🚧'],
    sceneBeschreibung: 'Ein großer Hund bellt laut hinter dem Zaun',
    wrongEmoji: '😄',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['ängstlich', 'glücklich', 'wütend'],
    richtig: 'ängstlich',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'girl',
    charEmotion: 'surprised',
    sceneEmojis: ['🎂', '🎉', '🎊'],
    sceneBeschreibung: 'Das Kind bekommt eine Geburtstagsüberraschung',
    wrongEmoji: '😴',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['überrascht', 'müde', 'traurig'],
    richtig: 'überrascht',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'boy',
    charEmotion: 'proud',
    sceneEmojis: ['🧩', '✅'],
    sceneBeschreibung: 'Das Kind hat das Puzzle fertig gebaut',
    wrongEmoji: '😢',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['stolz', 'traurig', 'ängstlich'],
    richtig: 'stolz',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'kid',
    charEmotion: 'bored',
    sceneEmojis: ['⏰', '🧒', '💺'],
    sceneBeschreibung: 'Das Kind muss sehr lange warten',
    wrongEmoji: '😀',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['ungeduldig', 'glücklich', 'stolz'],
    richtig: 'ungeduldig',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'girl',
    charEmotion: 'proud',
    sceneEmojis: ['🎁', '🖍️', '💝'],
    sceneBeschreibung: 'Das Kind hat ein Geschenk für Mama gebastelt',
    wrongEmoji: '😡',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['stolz', 'wütend', 'ängstlich'],
    richtig: 'stolz',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'boy',
    charEmotion: 'sad',
    sceneEmojis: ['🍦', '💧', '😲'],
    sceneBeschreibung: 'Das Eis fällt auf den Boden',
    wrongEmoji: '😄',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['traurig', 'glücklich', 'aufgeregt'],
    richtig: 'traurig',
  },
  {
    type: 'situation-emoji-check',
    charVariant: 'kid',
    charEmotion: 'happy',
    sceneEmojis: ['👫', '🏠', '🎮'],
    sceneBeschreibung: 'Ein Freund kommt zum Spielen vorbei',
    wrongEmoji: '😡',
    frage: 'Wie fühlt sich das Kind wirklich?',
    optionen: ['glücklich', 'wütend', 'traurig'],
    richtig: 'glücklich',
  },
]

// Kategorie 2: Nur Situation → Emotion erraten
const KAT2 = [
  {
    type: 'situation-erraten',
    charVariant: 'kid',
    charEmotion: 'happy',
    sceneEmojis: ['🎁', '🎀'],
    sceneBeschreibung: 'Kind bekommt ein Geschenk',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['glücklich', 'wütend', 'traurig'],
    richtig: 'glücklich',
  },
  {
    type: 'situation-erraten',
    charVariant: 'boy',
    charEmotion: 'sad',
    sceneEmojis: ['⚽', '🌊', '😱'],
    sceneBeschreibung: 'Der Ball rollt in den Fluss',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['traurig', 'glücklich', 'stolz'],
    richtig: 'traurig',
  },
  {
    type: 'situation-erraten',
    charVariant: 'kid',
    charEmotion: 'scared',
    sceneEmojis: ['👾', '🛏️', '🌙'],
    sceneBeschreibung: 'Das Kind sieht ein Monster unter dem Bett',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['ängstlich', 'glücklich', 'ungeduldig'],
    richtig: 'ängstlich',
  },
  {
    type: 'situation-erraten',
    charVariant: 'girl',
    charEmotion: 'proud',
    sceneEmojis: ['🏆', '🎮', '✅'],
    sceneBeschreibung: 'Das Kind gewinnt ein Spiel',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['stolz', 'traurig', 'ängstlich'],
    richtig: 'stolz',
  },
  {
    type: 'situation-erraten',
    charVariant: 'boy',
    charEmotion: 'bored',
    sceneEmojis: ['🥦', '🍽️', '😬'],
    sceneBeschreibung: 'Das Kind muss Gemüse essen',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['unzufrieden', 'glücklich', 'stolz'],
    richtig: 'unzufrieden',
  },
  {
    type: 'situation-erraten',
    charVariant: 'kid',
    charEmotion: 'love',
    sceneEmojis: ['🤗', '👩', '💕'],
    sceneBeschreibung: 'Das Kind umarmt Mama',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['liebevoll', 'ängstlich', 'wütend'],
    richtig: 'liebevoll',
  },
  {
    type: 'situation-erraten',
    charVariant: 'girl',
    charEmotion: 'bored',
    sceneEmojis: ['🛒', '⏰', '😫'],
    sceneBeschreibung: 'Das Kind wartet lange im Supermarkt',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['ungeduldig', 'glücklich', 'traurig'],
    richtig: 'ungeduldig',
  },
  {
    type: 'situation-erraten',
    charVariant: 'boy',
    charEmotion: 'confused',
    sceneEmojis: ['📝', '❓', '🤔'],
    sceneBeschreibung: 'Die Hausaufgabe ist zu schwer',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['verwirrt', 'glücklich', 'stolz'],
    richtig: 'verwirrt',
  },
  {
    type: 'situation-erraten',
    charVariant: 'kid',
    charEmotion: 'proud',
    sceneEmojis: ['🧩', '⭐', '✨'],
    sceneBeschreibung: 'Das Kind löst ein schwieriges Puzzle',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['stolz', 'ängstlich', 'traurig'],
    richtig: 'stolz',
  },
  {
    type: 'situation-erraten',
    charVariant: 'girl',
    charEmotion: 'sad',
    sceneEmojis: ['😤', '👫', '💔'],
    sceneBeschreibung: 'Ein Freund sagt etwas Gemeines',
    frage: 'Wie fühlt sich das Kind?',
    optionen: ['traurig', 'glücklich', 'stolz'],
    richtig: 'traurig',
  },
]

// Kategorie 3: Emoji → Situation wählen
const KAT3 = [
  {
    type: 'emoji-zu-situation',
    charVariant: 'kid',
    charEmotion: 'sad',
    emoji: '😢',
    frage: 'Wann fühlt sich ein Kind so?',
    optionen: [
      { emojis: ['🍦', '💧'], text: 'Eis fällt runter',       richtig: true  },
      { emojis: ['🎁', '😊'], text: 'Geschenk bekommen',      richtig: false },
      { emojis: ['🎂', '🎉'], text: 'Geburtstag feiern',      richtig: false },
    ],
  },
  {
    type: 'emoji-zu-situation',
    charVariant: 'boy',
    charEmotion: 'angry',
    emoji: '😡',
    frage: 'Wann fühlt sich ein Kind so?',
    optionen: [
      { emojis: ['🧸', '👋'], text: 'Spielzeug wird weggenommen', richtig: true  },
      { emojis: ['🍦', '😋'], text: 'Eis essen',                   richtig: false },
      { emojis: ['🎁', '😃'], text: 'Geschenk bekommen',           richtig: false },
    ],
  },
  {
    type: 'emoji-zu-situation',
    charVariant: 'girl',
    charEmotion: 'surprised',
    emoji: '😲',
    frage: 'Wann fühlt sich ein Kind so?',
    optionen: [
      { emojis: ['🎂', '🎊'], text: 'Überraschungsparty',   richtig: true  },
      { emojis: ['😴', '🌙'], text: 'Schlafen gehen',        richtig: false },
      { emojis: ['🦷', '🪥'], text: 'Zähne putzen',          richtig: false },
    ],
  },
  {
    type: 'emoji-zu-situation',
    charVariant: 'kid',
    charEmotion: 'proud',
    emoji: '😤',
    frage: 'Wann fühlt sich ein Kind so?',
    optionen: [
      { emojis: ['🏆', '⭐'], text: 'Wettbewerb gewonnen',   richtig: true  },
      { emojis: ['😢', '💔'], text: 'Spielzeug verloren',     richtig: false },
      { emojis: ['🛒', '⏰'], text: 'Lange warten',           richtig: false },
    ],
  },
  {
    type: 'emoji-zu-situation',
    charVariant: 'boy',
    charEmotion: 'scared',
    emoji: '😨',
    frage: 'Wann fühlt sich ein Kind so?',
    optionen: [
      { emojis: ['⚡', '🌩️'], text: 'Gewitter in der Nacht',  richtig: true  },
      { emojis: ['🍕', '😋'], text: 'Pizza essen',              richtig: false },
      { emojis: ['🌅', '☀️'], text: 'Schöner Tag',              richtig: false },
    ],
  },
  {
    type: 'emoji-zu-situation',
    charVariant: 'girl',
    charEmotion: 'happy',
    emoji: '😊',
    frage: 'Wann fühlt sich ein Kind so?',
    optionen: [
      { emojis: ['👫', '🎮'], text: 'Mit Freund spielen',    richtig: true  },
      { emojis: ['💥', '😱'], text: 'Spielzeug kaputt',       richtig: false },
      { emojis: ['⏰', '😫'], text: 'Lange warten müssen',    richtig: false },
    ],
  },
]

// Kategorie 4: Emotion + Entscheidung (Multi-Select)
const KAT4 = [
  {
    type: 'emotion-entscheidung',
    charVariant: 'boy',
    charEmotion: 'sad',
    sceneEmojis: ['⚽', '😮', '😢'],
    sceneBeschreibung: 'Ein Kind hat aus Versehen den Ball weggenommen',
    frage: 'Wie könnte sich das Kind fühlen?',
    optionen: ['traurig', 'wütend', 'überrascht', 'glücklich'],
    richtig: ['traurig', 'wütend', 'überrascht'],
    erklaerung: 'Manchmal fühlt man viele Gefühle gleichzeitig!',
  },
  {
    type: 'emotion-entscheidung',
    charVariant: 'girl',
    charEmotion: 'surprised',
    sceneEmojis: ['🎁', '🎉', '😲'],
    sceneBeschreibung: 'Alle singen Geburtstagslied — das Kind wusste es nicht!',
    frage: 'Wie könnte sich das Kind fühlen?',
    optionen: ['überrascht', 'glücklich', 'ängstlich', 'traurig'],
    richtig: ['überrascht', 'glücklich'],
    erklaerung: 'Überraschungen können glücklich UND aufgeregt machen!',
  },
  {
    type: 'emotion-entscheidung',
    charVariant: 'kid',
    charEmotion: 'confused',
    sceneEmojis: ['🏫', '📚', '😟'],
    sceneBeschreibung: 'Erster Tag in der neuen Schule',
    frage: 'Wie könnte sich das Kind fühlen?',
    optionen: ['ängstlich', 'aufgeregt', 'traurig', 'stolz'],
    richtig: ['ängstlich', 'aufgeregt'],
    erklaerung: 'Neue Erlebnisse machen manchmal gleichzeitig Angst und Vorfreude!',
  },
  {
    type: 'emotion-entscheidung',
    charVariant: 'boy',
    charEmotion: 'proud',
    sceneEmojis: ['🏆', '👨‍👩‍👦', '📸'],
    sceneBeschreibung: 'Das Kind hat gewonnen und die Eltern freuen sich',
    frage: 'Wie könnte sich das Kind fühlen?',
    optionen: ['stolz', 'glücklich', 'ängstlich', 'traurig'],
    richtig: ['stolz', 'glücklich'],
    erklaerung: 'Erfolge machen uns stolz und glücklich!',
  },
]

// Kategorie 5: Empathie — Was hilft?
const KAT5 = [
  {
    type: 'empathie-reaktion',
    charVariant: 'girl',
    charEmotion: 'sad',
    sceneEmojis: ['😢', '🧒'],
    emotion: 'traurig',
    frage: 'Das Kind ist traurig. Was hilft?',
    optionen: [
      { emoji: '🤗', text: 'Umarmen',    richtig: true  },
      { emoji: '😂', text: 'Auslachen',  richtig: false },
      { emoji: '🙄', text: 'Ignorieren', richtig: false },
      { emoji: '🤝', text: 'Helfen',     richtig: true  },
    ],
    erklaerung: 'Umarmen und helfen macht traurige Menschen glücklicher!',
  },
  {
    type: 'empathie-reaktion',
    charVariant: 'boy',
    charEmotion: 'angry',
    sceneEmojis: ['😠', '🧒'],
    emotion: 'wütend',
    frage: 'Das Kind ist wütend. Was ist gut?',
    optionen: [
      { emoji: '🗣️', text: 'Reden',          richtig: true  },
      { emoji: '🤬', text: 'Auch wütend sein', richtig: false },
      { emoji: '🧘', text: 'Tief atmen',       richtig: true  },
      { emoji: '🏃', text: 'Weglaufen',        richtig: false },
    ],
    erklaerung: 'Über Gefühle reden und tief atmen hilft bei Wut!',
  },
  {
    type: 'empathie-reaktion',
    charVariant: 'kid',
    charEmotion: 'scared',
    sceneEmojis: ['😨', '🌙'],
    emotion: 'ängstlich',
    frage: 'Das Kind hat Angst. Was hilft?',
    optionen: [
      { emoji: '🤗', text: 'Dabei sein',    richtig: true  },
      { emoji: '😱', text: 'Erschrecken',   richtig: false },
      { emoji: '💬', text: 'Zuhören',       richtig: true  },
      { emoji: '🏃', text: 'Weggehen',      richtig: false },
    ],
    erklaerung: 'Bei jemandem sein und zuhören nimmt die Angst!',
  },
  {
    type: 'empathie-reaktion',
    charVariant: 'girl',
    charEmotion: 'happy',
    sceneEmojis: ['😊', '🏆'],
    emotion: 'stolz',
    frage: 'Das Kind ist stolz auf sich. Was ist schön?',
    optionen: [
      { emoji: '👏', text: 'Klatschen',     richtig: true  },
      { emoji: '😒', text: 'Neidisch sein', richtig: false },
      { emoji: '😄', text: 'Mitfreuen',     richtig: true  },
      { emoji: '🙄', text: 'Egal sein',     richtig: false },
    ],
    erklaerung: 'Klatschen und mitfreuen zeigt, dass man sich füreinander freut!',
  },
]

// ─── Export ───────────────────────────────────────────────────────────────────
export const KARTEN_KATEGORIEN = [
  {
    id: 1,
    missionId: 'emotionen-karten-kat1',
    title: 'Passt das?',
    icon: '🤔',
    desc: 'Stimmt das Emoji zur Situation?',
    color: '#4f46e5',
    bg: '#eef2ff',
    border: '#a5b4fc',
    fragen: KAT1,
  },
  {
    id: 2,
    missionId: 'emotionen-karten-kat2',
    title: 'Wie fühlt sich das Kind?',
    icon: '😊',
    desc: 'Rate die richtige Emotion!',
    color: '#10b981',
    bg: '#ecfdf5',
    border: '#6ee7b7',
    fragen: KAT2,
  },
  {
    id: 3,
    missionId: 'emotionen-karten-kat3',
    title: 'Wann fühlt man so?',
    icon: '🎭',
    desc: 'Zum Emoji die richtige Situation',
    color: '#f97316',
    bg: '#fff7ed',
    border: '#fdba74',
    fragen: KAT3,
  },
  {
    id: 4,
    missionId: 'emotionen-karten-kat4',
    title: 'Viele Gefühle?',
    icon: '💭',
    desc: 'Manchmal fühlt man mehreres!',
    color: '#8b5cf6',
    bg: '#f5f3ff',
    border: '#c4b5fd',
    fragen: KAT4,
  },
  {
    id: 5,
    missionId: 'emotionen-karten-kat5',
    title: 'Was hilft?',
    icon: '❤️',
    desc: 'Lerne anderen zu helfen',
    color: '#ec4899',
    bg: '#fdf2f8',
    border: '#f9a8d4',
    fragen: KAT5,
  },
]
